# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeId', models.AutoField(primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadLine', models.DateTimeField(blank=True, null=True)),
                ('prizeMoney', models.IntegerField(blank=True, null=True)),
                ('maxMembers', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionName', models.CharField(max_length=50, null=True)),
                ('optionText', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ParentEvent',
            fields=[
                ('parentEventId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamName', models.CharField(blank=True, max_length=50, null=True)),
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TechProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')])),
                ('mobileNumber', models.BigIntegerField()),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.College')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='members', to='Auth.TechProfile'),
        ),
        migrations.AddField(
            model_name='team',
            name='teamLeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamLeader', to='Auth.TechProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='parentEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.ParentEvent'),
        ),
    ]
