# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 20:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageLink', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('websiteLink', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sponsors',
            name='sponsorType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.SponsorshipType'),
        ),
    ]
