# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='optionsC',
            fields=[
                ('optionId', models.AutoField(primary_key=True, serialize=False)),
                ('optionText', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.questions')),
            ],
        ),
        migrations.AddField(
            model_name='questionresponses',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.optionsC'),
        ),
    ]
