# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponses',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionresponses',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='questionResponses',
        ),
    ]
