# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoption',
            old_name='optionText',
            new_name='optionDescription',
        ),
    ]
