# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 10:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_chutiyapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
