# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-20 12:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20170119_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='sponimage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshops',
            name='sponlink',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
