# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20170204_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionsc',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionresponses',
            name='option',
        ),
        migrations.RemoveField(
            model_name='questionresponses',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionresponses',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='optionsC',
        ),
        migrations.DeleteModel(
            name='questionResponses',
        ),
    ]
