# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 14:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20160921_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventoption',
            name='optionDescription',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='parentevent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
