# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20160922_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventOrder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentevent',
            name='nameSlug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='parentevent',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
