# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20170204_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionResponsesChutiya',
            fields=[
                ('responseId', models.AutoField(primary_key=True, serialize=False)),
                ('integerAnswer', models.CharField(blank=True, max_length=20, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.questions')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.quizResponses')),
            ],
        ),
    ]
