# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_way2smsaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='optionResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=50)),
                ('answer2', models.CharField(max_length=50)),
                ('answer3', models.CharField(max_length=50)),
                ('answer4', models.CharField(max_length=50)),
                ('answer5', models.CharField(max_length=50)),
                ('answer6', models.CharField(max_length=50)),
                ('answer7', models.CharField(max_length=50)),
                ('answer8', models.CharField(max_length=50)),
                ('answer9', models.CharField(max_length=50)),
                ('answer10', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Team')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True)),
                ('option1', models.TextField(blank=True)),
                ('option2', models.TextField(blank=True)),
                ('option3', models.TextField(blank=True)),
                ('option4', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('quizId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.quiz'),
        ),
    ]
