# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20160922_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoption',
            name='eventOptionOrder',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
