# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-05 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20170205_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='techprofile',
            name='notificationToken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
