# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_techprofile_notificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sponsors',
            name='order',
            field=models.SmallIntegerField(default=999),
        ),
        migrations.AddField(
            model_name='sponsorshiptype',
            name='order',
            field=models.SmallIntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='techprofile',
            name='year',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Passout(Only for Startup Fair)')]),
        ),
    ]
