# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20170124_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionresponses',
            name='attemptStatus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='optionresponses',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='activeStatus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
