# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 11:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_eventoption_eventoptionorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200, null=True)),
                ('accessToken', models.CharField(max_length=250, null=True)),
                ('profileImange', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.AddField(
            model_name='techprofile',
            name='fb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.FbConnect'),
        ),
    ]
