# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20160925_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbconnect',
            old_name='profileImange',
            new_name='profileImage',
        ),
    ]
