# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20170208_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatusa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=15)),
                ('ticketId', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('ticketPrice', models.IntegerField(blank=True, null=True)),
                ('timeStamp', models.CharField(blank=True, max_length=50, null=True)),
                ('ticketName', models.CharField(blank=True, max_length=65, null=True)),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.TechProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='tech',
        ),
        migrations.DeleteModel(
            name='PaymentStatus',
        ),
    ]
