# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-07 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_notifications'),
        ('Auth', '0006_auto_20170206_2046'),
        ('Auth', '0006_auto_20170207_1244'),
    ]

    operations = [
    ]
