# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-24 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20170124_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
