# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_auto_20170208_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
