# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-28 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_auto_20170124_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Way2smsAccount_Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('messages_left', models.IntegerField(default=100)),
            ],
        ),
    ]
