# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 23:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_forgotpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('lecturerName', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('lecturerBio', ckeditor.fields.RichTextField()),
                ('lectureType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionName', models.CharField(max_length=50, null=True)),
                ('optionDescription', ckeditor.fields.RichTextField()),
                ('eventOptionOrder', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('workshopId', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('dateTime', models.DateTimeField(null=True)),
                ('workshopFees', models.IntegerField(null=True)),
                ('maxMembers', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='maxMembers',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopoptions',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Workshops'),
        ),
    ]
