# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-27 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_quizteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizteam',
            name='slot',
            field=models.SmallIntegerField(default=0),
        ),
    ]
