# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-29 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_quizteam_slot'),
        ('Auth', '0008_way2smsaccount_premium'),
    ]

    operations = [
    ]
