# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_auto_20160928_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopTeam',
            fields=[
                ('teamName', models.CharField(blank=True, max_length=50, null=True)),
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(related_name='members_for_workshop', to='Auth.TechProfile')),
                ('teamLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamLeaderForWorkshop', to='Auth.TechProfile')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Workshops')),
            ],
        ),
    ]
