# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-30 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizteam',
            name='members',
        ),
        migrations.RemoveField(
            model_name='quizteam',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='way2smsaccount',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='way2smsaccount_premium',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='quizTeam',
        ),
    ]
