# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-09 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_sheetpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetpayment',
            name='ticketName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
