# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_event_nameslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='techprofile',
            name='technexId',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(null=True, related_name='members', to='Auth.TechProfile'),
        ),
    ]
