# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-10 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_auto_20170209_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='techprofile',
            name='arrivaldate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='confirmpart',
            field=models.ManyToManyField(blank=True, null=True, to='Auth.Event'),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='tshirtdata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='tshirtsize',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.TechProfile'),
        ),
    ]
