# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_auto_20170130_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizTeam',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('quizTeamId', models.CharField(blank=True, max_length=10, null=True)),
                ('quizAttemptStatus', models.SmallIntegerField(default=0)),
                ('slot', models.SmallIntegerField(default=0)),
                ('members', models.ManyToManyField(null=True, related_name='quizMembers', to='Auth.TechProfile')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.quiz')),
            ],
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='way2smsaccount',
            name='username',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='way2smsaccount_premium',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
