# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_auto_20160929_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshopoptions',
            old_name='eventOptionOrder',
            new_name='optionOrder',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventOrder',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventoption',
            name='eventOptionOrder',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parentevent',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
