# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_auto_20170220_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='pin',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
