# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-31 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_auto_20170131_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way2smsaccount',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='way2smsaccount_premium',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
