# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-01 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_auto_20170131_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionText', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='questionResponses',
            fields=[
                ('responseId', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.options')),
            ],
        ),
        migrations.CreateModel(
            name='quizResponses',
            fields=[
                ('responseId', models.AutoField(primary_key=True, serialize=False)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.quiz')),
                ('quizTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.quizTeam')),
            ],
        ),
        migrations.RemoveField(
            model_name='optionresponses',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='optionresponses',
            name='team',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='questionID',
            new_name='questionId',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option4',
        ),
        migrations.DeleteModel(
            name='optionResponses',
        ),
        migrations.AddField(
            model_name='questionresponses',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.quizResponses'),
        ),
        migrations.AddField(
            model_name='options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.questions'),
        ),
    ]
