# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-21 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_idcard_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='techProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auth.TechProfile'),
        ),
    ]
