# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_metatags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatags',
            name='content',
            field=models.TextField(),
        ),
    ]
