# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_auto_20161024_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatags',
            name='name',
            field=models.TextField(),
        ),
    ]
