# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-21 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_auto_20170221_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.Facility'),
        ),
    ]
