# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_auto_20161024_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatags',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
