# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_auto_20170201_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizteam',
            name='member1Email',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='quizteam',
            name='member2Email',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='quizteam',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='quizMembers', to='Auth.TechProfile'),
        ),
    ]
