# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_auto_20170221_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='tshirtStatus',
            field=models.BooleanField(default=False),
        ),
    ]
