# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-22 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0017_idcard_tshirtstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
