# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0017_auto_20161024_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='techprofile',
            name='botInfo',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
