# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 03:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0018_techprofile_botinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=65, null=True)),
                ('facebookLink', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('photo', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('designation', models.CharField(max_length=50)),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.TeamList')),
            ],
        ),
    ]
