# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-03 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0019_auto_20170203_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponses',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.questions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
