# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-03 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0020_auto_20170203_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='status',
        ),
        migrations.AddField(
            model_name='questions',
            name='integerAnswer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
