# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-03 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0021_auto_20170203_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='techprofile',
            name='apploginStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
