# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-27 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0022_auto_20161026_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='techprofile',
            name='city',
            field=models.CharField(default='varanasi', max_length=65),
        ),
    ]
