# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0023_quizteam2_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponses',
            name='quizTeam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auth.quizTeam2'),
        ),
    ]
