# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0024_auto_20161028_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
