# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0024_auto_20170204_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='id',
        ),
        migrations.AddField(
            model_name='options',
            name='optionId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
