# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0025_auto_20170204_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='optionId',
            new_name='id',
        ),
    ]
