# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 18:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0025_college_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlecture',
            name='photo',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
