# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-04 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0026_auto_20170204_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
