# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0026_guestlecture_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlecture',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
