# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0029_notification_readerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='startUpFair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(max_length=250)),
                ('teamName', models.CharField(max_length=35)),
                ('teamLeader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auth.TechProfile')),
            ],
        ),
        migrations.CreateModel(
            name='startUpMails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=65, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.startUpFair')),
            ],
        ),
    ]
