# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-01 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0036_auto_20161210_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='startupmails',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.StartUpFair'),
        ),
    ]
