# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 17:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0051_auto_20170107_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentevent',
            name='sponlink',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='startupmails',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.StartUpFair'),
        ),
    ]
