# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-08 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0054_auto_20170108_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='startupfair',
            name='description',
            field=models.CharField(default=datetime.datetime(2017, 1, 8, 8, 0, 2, 601864, tzinfo=utc), max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startupfair',
            name='interests',
            field=models.CharField(default=datetime.datetime(2017, 1, 8, 8, 0, 19, 585166, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startupfair',
            name='year',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startupfair',
            name='idea',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='startupmails',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.StartUpFair'),
        ),
    ]
