# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-08 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0055_auto_20170108_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupfair',
            name='bType',
            field=models.ManyToManyField(null=True, related_name='btype', to='Auth.BusinessType'),
        ),
        migrations.AddField(
            model_name='startupfair',
            name='pindusry',
            field=models.ManyToManyField(null=True, related_name='primary_industry', to='Auth.PrimaryIndustry'),
        ),
        migrations.AlterField(
            model_name='startupmails',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.StartUpFair'),
        ),
    ]
