# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-08 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0058_auto_20170108_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techprofile',
            options={'permissions': (('permission_code', 'Publicity portal'),)},
        ),
        migrations.AddField(
            model_name='startupfair',
            name='angelListUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='startupfair',
            name='crunchBaseUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='startupmails',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.StartUpFair'),
        ),
    ]
