# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-08 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0054_auto_20170108_0911'),
        ('Auth', '0059_auto_20170108_1015'),
    ]

    operations = [
    ]
