# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-11 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0063_auto_20170111_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abstractstatus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startupmails',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.StartUpFair'),
        ),
    ]
