# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-12 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0064_auto_20170111_1957'),
        ('Auth', '0066_auto_20170111_2109'),
    ]

    operations = [
    ]
