# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-12 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0068_auto_20170112_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('ticketId', models.CharField(max_length=100)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.TechProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='startupmails',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.StartUpFair'),
        ),
    ]
