# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-12 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0072_auto_20170112_2125'),
        ('Auth', '0072_auto_20170112_2124'),
    ]

    operations = [
    ]
